image: node:20.11.0

options:
  max-time: 10

definitions:
  steps:
    - step: &lint-test-build
        name: Lint, tests and build
        caches:
          - node
        size: 2x # more memory needed for unit tests
        script:
          - cd org.knime.ui.js
          - git submodule update --init --recursive
          - npm ci
          - npm run ci:lint-format
          - npm run coverage
          - npm run build
          - npm run audit
        artifacts:
          - org.knime.ui.js/dist/**


pipelines:
  pull-requests:
    '**':
      - step: *lint-test-build
  branches:
    '{master,releases/*}':
      - step: *lint-test-build