image: node:22.11.0 # using 22.11.0 because the experimental feature for importing ESM (enabled by default starting with node 22.12.0) significantly slows test execution in the pipeline (https://github.com/vitest-dev/vitest/issues/7302)

options:
  max-time: 20

definitions:
  steps:
    - step: &lint-test-build
        name: Lint, tests and build
        caches:
          - node
        size: 2x # more memory needed for unit tests
        script:
          - cd org.knime.ui.js
          - npm ci
          - npm run ci:lint-format
          - npm run coverage
          - npm run build
          - npm run audit
        artifacts:
          - org.knime.ui.js/dist/**


pipelines:
  pull-requests:
    '**':
      - step: *lint-test-build
  branches:
    '{master,releases/*}':
      - step: *lint-test-build